[package]
name = "pure_mbr"
description = "A library to parse the master boot record (MBR)"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/ChocolateLoverRaj/pure_mbr"
authors = ["Rajas Paranjpe"]
license = "AGPL-3.0-or-later"
categories = ["no-std", "embedded", "no-std::no-alloc", "filesystem", "parsing"]

[dependencies]
zerocopy = { version = "0.8.31", features = ["derive"] }
